"""empty message

Revision ID: 0e177b9255a5
Revises: cdac732f0a38
Create Date: 2018-08-01 02:11:57.616634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e177b9255a5'
down_revision = 'cdac732f0a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('user_type', sa.Enum('guess', 'supervisor', 'admin'), nullable=True))
    op.create_unique_constraint(None, 'user', ['google_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'last_login_date')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###
