"""empty message

Revision ID: f59255f459d2
Revises: a01f3deb9e1f
Create Date: 2018-08-16 23:15:59.382086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59255f459d2'
down_revision = 'a01f3deb9e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('birthday', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'birthday')
    # ### end Alembic commands ###
